[DON'T MERGE WORK IN PROGRESS] Feature/89 support stored proc
kdhrubo/db2rest pull request #103
Opened 2024-01-08 12:34 UTC by souravroy

Support for Stored procedure and function calls.

2024-01-08 12:46 UTC, thadguidry commented
In the future, you can use GitHub web interface to set a PR as a Draft, instead of regular PR.  I've done this for you now however.

2024-01-08 13:22 UTC, souravroy commented
Thank you for letting me know @thadguidry

2024-01-08 16:31 UTC, kdhrubo commented on pom.xml
Do we need this dependency. The starter is already present

<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jdbc</artifactId>
        </dependency>

2024-01-08 16:35 UTC, kdhrubo commented on src/main/java/com/homihq/db2rest/rest/rpc/SubRoutine.java
What is the advantage of validating the subroutine? Does this require an additional trip to the database?
Is it not worthwhile to just package the variables and let database verify everything as it is the key function of db.

2024-01-08 16:36 UTC, kdhrubo commented on src/main/java/com/homihq/db2rest/rest/rpc/SubRoutine.java
> +        try(var connection = Objects.requireNonNull(jdbcTemplate.getDataSource()).getConnection()) {
What happens to the connection and resultset object? are they closed automatically?

2024-01-08 16:36 UTC, kdhrubo requested changes
Looks good in most parts. Please review and the comments and we should merge this today.

2024-01-08 17:30 UTC, kdhrubo commented on src/main/java/com/homihq/db2rest/rest/rpc/SubRoutine.java
Lets remove the call and rely on the db. 
One of the goal of db2rest is to be blazing fast.

2024-01-08 17:42 UTC, souravroy commented on pom.xml
> Do we need this dependency. The starter is already present
> 
> org.springframework.boot spring-boot-starter-jdbc

Removed `spring-jdbc` dependency. Earlier it won't compile without this jar, I'm not sure what has changed, it's perfectly fine without `spring-jdbc` this time

2024-01-08 18:06 UTC, souravroy commented on src/main/java/com/homihq/db2rest/rest/rpc/SubRoutine.java
Removed validation

2024-01-08 18:11 UTC, kdhrubo approved these changes

2024-01-08 18:17 UTC, merged

2024-01-09 03:54 UTC, thadguidry commented
@souravroy @kdhrubo It's often better to just use try-with-resources.  As long as you declare and init inside the `try` then those resources will be auto-closed after the `try` execution.  You can even have effectively final variables as of Java 9.
https://www.baeldung.com/java-try-with-resources